/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;

import Connections.DataBase;
import KategorijaKorisnika.KategorijaKorisnika;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Toni
 */
public class Admin extends javax.swing.JPanel {
    public DataBase data;
    public Pattern inCase;
    public Matcher control;
    public Pattern inCase1;
    public Matcher control1;
    public Pattern inCase2;
    public Matcher control2;
    public Pattern inCase3;
    public Matcher control3;
    public KategorijaKorisnika kategorija;
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        jRadioButton2.setSelected(true);
        try {
            data = DataBase.getInstance();
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Izbriši");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTextField3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Unesi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ime:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Prezime:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Korisničko ime:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Lozinka:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ponovite lozinku:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Unos korisnika");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Za brisanje unesite korisničko ime");

        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jPasswordField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Rukovalac sistemom");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Običan korisnik");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Kategorija korisnika:");

        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setText("Nazad");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(" Statistika prijava");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Pogrešna lozinka!");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nepravilan unos!");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nepravilan unos!");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel14.setText("Unesite minimalno šest kataktera (slova + brojevi)");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jLabel15.setText("Unesite minimalno osam karaktera (slova + brojevi)");

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Neispravan unos!");

        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Nepravilan unos!");

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Nepravilan unos!");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel11)
                            .addComponent(jRadioButton2))
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPasswordField1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)))
                                        .addGap(25, 25, 25)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addGap(7, 7, 7)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18))
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jButton3)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String korisnickoIme = null;
        PreparedStatement ps;
        ResultSet rs;
        PreparedStatement ps1;
        ResultSet rs1;
        try {
            if(!jTextField2.getText().isEmpty()){
                ps = data.connection.prepareStatement("select korisnicko_ime from zaposleni where binary korisnicko_ime = ?");
                ps.setString(1, jTextField2.getText());
                rs = ps.executeQuery();
                while(rs.next()){
                    korisnickoIme = rs.getString("korisnicko_ime");
                }
                jLabel18.setForeground(Color.decode("13421772"));
            }else{
                jLabel18.setText("Unesite korisničko ime!");
                jLabel18.setForeground(Color.red);
                return;
            }
            
            if(korisnickoIme != null){
                ps1 = data.connection.prepareStatement("delete from zaposleni where binary korisnicko_ime = ?");
                ps1.setString(1, jTextField2.getText());
                ps1.execute();
                jLabel18.setForeground(Color.decode("13421772"));
            }else{
                jLabel18.setText("Nepostojeći korisnik!");
                jLabel18.setForeground(Color.red);
            }   
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PreparedStatement ps;
            PreparedStatement ps1;
            ResultSet rs;
            
            String ime = jTextField1.getText();
            inCase = Pattern.compile("^[A-ZŠČĆĐŽ][a-zščžćđ]*$");
            control = inCase.matcher(ime);
            
            String prezime = jTextField3.getText();
            inCase1 = Pattern.compile("^[A-ZŠČĆĐŽ][a-zščžćđ]*$");
            control1 = inCase1.matcher(prezime);
            
            String korisnickoIme = jTextField2.getText();
            inCase3 = Pattern.compile("^(?=.*[A-ZŠČĆĐŽa-zščžćđ])[A-ZŠČĆĐŽa-zščžćđ\\d$-_*?.,!@#$&^+|;°~:%=]{6,18}$");
            control3 = inCase3.matcher(korisnickoIme);
            
            String lozinka = jPasswordField1.getText();
            inCase2 = Pattern.compile("^(?=.*[A-ZŠČĆĐŽa-zščžćđ])[A-ZŠČĆĐŽa-zščžćđ\\d$-_*?.,!@#$&^+|;°~:%=]{8,20}$");
            control2 = inCase2.matcher(lozinka);
            
            boolean password = false;
            boolean imeControl = false;
            boolean prezimeControl = false;
            boolean lozinkaControl = false;
            boolean korisnickoImeControl = true;
            List<String> korisnickoImeList = new ArrayList<String>();
            
            if(jPasswordField1.getText().equals(jPasswordField2.getText()) && !jPasswordField1.getText().isEmpty() && !jPasswordField2.getText().isEmpty()){
                password = true;
                jLabel1.setForeground(Color.decode("13421772"));
            }else{
                jLabel1.setForeground(Color.red);
            }
            
            if(control2.matches() && !jPasswordField1.getText().isEmpty()){
                lozinkaControl = true;
                jLabel17.setForeground(Color.decode("13421772"));
            }else{
                jLabel17.setForeground(Color.red);
            }
            
            if(control.matches() &&  !jTextField1.getText().isEmpty()){
                imeControl = true;
                jLabel2.setForeground(Color.decode("13421772"));
            }else{
                jLabel2.setForeground(Color.red);
            }
            
            if(control1.matches() && !jTextField3.getText().isEmpty()){
                prezimeControl = true;
                jLabel3.setForeground(Color.decode("13421772"));
            }else{
                jLabel3.setForeground(Color.red);
            }
            
            if(control3.matches() && !jTextField2.getText().isEmpty()){
                ps1 = data.connection.prepareStatement("select * from zaposleni");
                rs = ps1.executeQuery();
                while(rs.next()){
                    korisnickoImeList.add(rs.getString("korisnicko_ime"));
                }
                
                for(String i : korisnickoImeList){
                    if(jTextField2.getText().equals(i)){
                        korisnickoImeControl = false;
                        break;
                    }
                }
                
                if(korisnickoImeControl == true){
                    jLabel18.setForeground(Color.decode("13421772"));
                }else{
                    jLabel18.setText("Korisnik već postoji");
                        jLabel18.setForeground(Color.red);
                }
                
            }else{
                jLabel18.setText("Nepravilan unos!");
                jLabel18.setForeground(Color.red);
            }
            
            if(password == true && imeControl == true && prezimeControl == true && lozinkaControl == true && korisnickoImeControl == true){
            ps = data.connection.prepareStatement("insert into zaposleni(ime,prezime,korisnicko_ime,lozinka,datum,kategorija) values (?,?,?,?,null,?)");
                ps.setString(1, ime);
                ps.setString(2, jTextField3.getText());
                ps.setString(3, jTextField2.getText());
                ps.setString(4, jPasswordField1.getText());
                
                if(jRadioButton2.isSelected() != false){
                    ps.setInt(5, kategorija.ObicanKorisnik.value);
                }

                if(jRadioButton1.isSelected() != false){
                    ps.setInt(5, kategorija.RukovalacSistemom.value);
                }

                ps.execute();
                jLabel1.setForeground(Color.decode("13421772"));
                jLabel2.setForeground(Color.decode("13421772"));
                jLabel3.setForeground(Color.decode("13421772"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        List<Integer> control = new ArrayList<Integer>();
        boolean kategorija = false;
        
        try {
            PreparedStatement ps = data.connection.prepareStatement("select * from zaposleni");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                control.add(rs.getInt("kategorija"));    
            }
            
            for(int i:control){
                if(i == 1){
                    kategorija = true;
                    break;
                }
            }
            
            if(kategorija == true){
                MyFrame.frame.setContentPane(new Login());
                MyFrame.frame.setResizable(false);
                MyFrame.frame.revalidate();
            }else{
                jLabel12.setText("<HTML>Nije moguce naputiti unos korisnika .Nema rukovaoca sistema u bazi!</HTML>");
                jLabel12.setForeground(Color.red);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            MyFrame.frame.setContentPane(new Preview());
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        MyFrame.frame.setResizable(false);
        MyFrame.frame.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
