/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;
import Connections.DataBase;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Toni
 */
public class Login extends javax.swing.JPanel {
    public DataBase data;
    /**
     * Creates new form Login
     */
    public Login() throws SQLException {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setMinimumSize(this.getMinimumSize());
        this.setFocusable(true);
        data = DataBase.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Prijava");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Korisnicko ime:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lozinka:");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Neispravno korisničko ime!");

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Neispravna lozinka!");

        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Unos korisnika");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Neovlašćen korisnik");

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Neispravno korisničko ime ili lozinka");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Neovlašćen pristup!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String lozinka = null;
        String korisnickoIme = null;
        try {
            if(!jTextField1.getText().isEmpty() && !jPasswordField1.getText().isEmpty()){
            
                PreparedStatement ps = data.connection.prepareStatement("select * from zaposleni where binary korisnicko_ime = ? and binary lozinka = ?");
                ps.setString(1, jTextField1.getText());
                ps.setString(2, jPasswordField1.getText());
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    korisnickoIme = rs.getString("korisnicko_ime");
                    lozinka = rs.getString("lozinka");
                }
                
            if(korisnickoIme != null && lozinka != null){
                
                //Seting present time from last login to username
                    data.connection.prepareStatement("update zaposleni set datum = now() where binary korisnicko_ime = '"+jTextField1.getText()+"'").execute();
                    MyFrame.frame.setContentPane(new Home());
                    MyFrame.frame.setResizable(true);
                    MyFrame.frame.revalidate();
            }else{
                jLabel6.setForeground(Color.red);
            }
        }else{
                jLabel6.setForeground(Color.red);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rukovalacSistemom = 0;
        String lozinka = null;
        String korisnickoIme = null;
        
        
        try {
            if(!jTextField1.getText().isEmpty() && !jPasswordField1.getText().isEmpty()){
            
                PreparedStatement ps = data.connection.prepareStatement("select * from zaposleni where binary korisnicko_ime = ? and binary lozinka = ?");
                ps.setString(1, jTextField1.getText());
                ps.setString(2, jPasswordField1.getText());
                ResultSet rs = ps.executeQuery();
                while(rs.next()){
                    korisnickoIme = rs.getString("korisnicko_ime");
                    lozinka = rs.getString("lozinka");
                }
                
            if(korisnickoIme != null && lozinka != null){
                PreparedStatement ps2 = data.connection.prepareStatement("select kategorija from zaposleni where binary korisnicko_ime = ? and binary lozinka = ?");
                ps2.setString(1, jTextField1.getText());
                ps2.setString(2, jPasswordField1.getText());
                ResultSet rs2 = ps2.executeQuery();
                while(rs2.next()){
                    rukovalacSistemom = rs2.getInt("kategorija");
                }

                if(rukovalacSistemom == 1){
                    MyFrame.frame.setContentPane(new Admin());
                    MyFrame.frame.setResizable(false);
                    MyFrame.frame.revalidate();
                }else{
                    jLabel6.setForeground(Color.decode("13421772"));
                    jLabel7.setForeground(Color.red);
                }
            }else{
                jLabel7.setForeground(Color.decode("13421772"));
                jLabel6.setForeground(Color.red);
            }
        }else{
                jLabel6.setForeground(Color.red);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
